### ISSUE TITLE
`wallet.ethGetaddress is not a function` error on non-EVM wallets

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#2495]
### Overview

When connected to a wallet that does not support EVM chains (e.g Keplr), the following errors are thrown:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/17035424/185678776-9646d44b-8d0d-48b7-9c41-63dda97920f1.png">

### References and additional details

Caused by https://github.com/shapeshift/web/commit/d63dc49fb5beb9b3fba4913de70306f3a520ce89#diff-6c36dba312b06e690f92edb784df2a088acf182f22a9ddea49832f491c3ae9e7R137 - we're assuming an `EthereumChainAdapter` but could be in the context of a wallet where this is invalid.

`supportsEth` should be used for wallet feature detection:

https://github.com/shapeshift/hdwallet/blob/27a4fd31b590051a18cec2387a4574ec05cb546d/packages/hdwallet-core/src/wallet.ts#L118

### Acceptance Criteria

- Proper control flow is implemented so that we don't call the adapter methods from an adapter that the wallet does not support
